# Uncomment the next line to define a global platform for your project
# platform :ios, ‚10.3‘

target 'FoodCheck' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodCheck
    pod 'Alamofire', '~> 4.4.0'
    pod 'OAuthSwift', '~> 1.1.0'
    pod 'OAuthSwiftAlamofire'
    pod 'RealmSwift', '~> 2.7.0'


end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.1'
        end
    end
end
